
title: gallery

columns:
  - width: 1/2
    sections:
      content:
        type: fields
        fields:
          caption:
            label: 说明
            type: textarea
            size: medium
  - width: 1/2
    sections:
      meta:
        type: fields
        fields:
          alt:
            label: 替代文本
            type: text
          imgid:
            label: 图像id
            type: text
          link:
            label: 链接
            type: url
